### ISSUE TITLE
Compiling with intel/17.0.4, impi/17.3 and mkl/17.3

### ISSUE THREAD

**Issue by aldubois** [eth-cscs/COSMA#64]
Hi,

I run into a few minor errors while trying to compile with intel/17.0.4 and impi/17.3.
The first one is in grid2grid: kabicm/grid2grid/issues/10

The others are:
```
src/cosma/strategy.cpp(244): error: no instance of constructor "std::vector<_Tp, _Alloc>::vector [with _Tp=std::tuple<long long, int, char>, _Alloc=std::allocator<std::tuple<long long, int, char>>]" matches the argument list
            argument types are: ({...}, {...}, {...})
      std::vector<dim_pair> dims = {{m, divm, 'B'}, {n, divn, 'A'}, {k, divk, 'C'}};

src/cosma/strategy.cpp(278): error: copy-list-initialization cannot use a constructor marked "explicit"
      return {memory_A, memory_B, memory_C};
```

A+,
Alex
